pipeline{
    agent any
    stages{
        stage('Deploy') {
            steps {
                sh '''
                oc project rkkois-deploy-strategies
                oc start-build greeting-service --follow --wait
                '''
            }
       }
    }
}

